apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sample
spec:
  schedule: '*/3 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: 'docker/whalesay:latest'
            command:
            - cowsay
            args:
            - hello
            - hideto0710
          restartPolicy: Never
