backend:
  name: github
  repo: mudazukai/gitops-meets-cms
  branch: master

media_folder: "images"
public_folder: "/images"

collections:
- name: "jobs"
  label: "Jobs"
  folder: "jobs"
  create: true
  identifier_field: "metadata.name"
  fields:
  - {label: "APIVersion", name: "apiVersion", widget: "hidden", default: "batch/v1beta1"}
  - {label: "Kind", name: "kind", widget: "hidden", default: "CronJob"}
  - label: "Metadata"
    name: "metadata"
    widget: "object"
    fields:
    - {label: "Name", name: "name", widget: "string"}
  - label: "Spec"
    name: "spec"
    widget: "object"
    fields:
    - {label: "Schedule", name: "schedule", widget: "string"}
    - label: "JobTemplate"
      name: "jobTemplate"
      widget: "object"
      fields:
      - label: "Spec"
        name: "spec"
        widget: "object"
        fields:
        - label: "Template"
          name: "template"
          widget: "object"
          fields:
          - label: "Spec"
            name: "spec"
            widget: "object"
            fields:
            - label: "Containers"
              name: "containers"
              widget: "list"
              fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Image", name: "image", widget: "string"}
              - {label: "Args", name: "args", widget: "list"}
              - {label: "RestartPolicy", name: "restartPolicy", widget: "string"}
