backend:
  name: github
  repo: mudazukai/gitops-meets-cms
  branch: master

media_folder: "images"
public_folder: "/images"
publish_mode: editorial_workflow

collections:
  - name: "jobs"
    label: "Jobs"
    folder: "jobs"
    create: true
    identifier_field: "metadata.name"
    extension: "yaml"
    fields:
      - {label: "APIVersion", name: "apiVersion", widget: "hidden", default: "batch/v1beta1"}
      - {label: "Kind", name: "kind", widget: "hidden", default: "CronJob"}
      - label: "Metadata"
        name: "metadata"
        widget: "object"
        fields:
          - {label: "Name", name: "name", widget: "string"}
      - label: "Spec"
        name: "spec"
        widget: "object"
        fields:
          - {label: "Schedule", name: "schedule", widget: "string"}
          - label: "JobTemplate"
            name: "jobTemplate"
            widget: "object"
            fields:
              - label: "Spec"
                name: "spec"
                widget: "object"
                fields:
                  - label: "Template"
                    name: "template"
                    widget: "object"
                    fields:
                      - label: "Spec"
                        name: "spec"
                        widget: "object"
                        fields:
                          - label: "Containers"
                            name: "containers"
                            widget: "list"
                            fields:
                              - {label: "Name", name: "name", widget: "hidden", default: "hello"}
                              - {label: "Image", name: "image", widget: "hidden", default: "docker/whalesay:latest"}
                              - label: "Args"
                                name: "args"
                                widget: "list"
                                field: {label: "Arg", name: "arg", widget: "string"}
                          - {label: "RestartPolicy", name: "restartPolicy", widget: "hidden", default: "Never"}

  - name: "simplejobs"
    label: "SimpleJobs"
    folder: "simple-jobs"
    create: true
    identifier_field: "metadata.name"
    extension: "yaml"
    fields:
      - {label: "APIVersion", name: "apiVersion", widget: "hidden", default: "batch.hideto0710.github.com/v1"}
      - {label: "Kind", name: "kind", widget: "hidden", default: "SimpleJob"}
      - label: "Metadata"
        name: "metadata"
        widget: "object"
        fields:
          - {label: "Name", name: "name", widget: "string"}
      - label: "Spec"
        name: "spec"
        widget: "object"
        fields:
          - {label: "Schedule", name: "schedule", widget: "string"}
          - {label: "Name", name: "name", widget: "string"}
